pipeline {
    agent any

    tools {
        maven 'M3'   // Your Maven installation in Jenkins
        jdk 'jdk17'  // Your Java version
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/AyushN08/Ayush_Jenkins_Exp.git'
            }
        }

        stage('Build & Package') {
            steps {
                // Clean, compile, and package into jar
                bat 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }

        stage('Archive') {
            steps {
                // Archive the jar generated by Maven
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
